"""Configuration and pattern definitions"""

from .patterns import (
    DOMAIN_PATTERNS,
    NEURODIVERGENT_PATTERNS,
    BIO_KEYWORDS,
    CONSCIOUSNESS_TYPES,
    TIME_PATTERNS,
    TIME_CONVERSIONS,
    IMPLICIT_TIME_INDICATORS,
    IMPLICIT_TIME_VALUES,
    PROFANITY_INDICATORS
)

__all__ = [
    'DOMAIN_PATTERNS',
    'NEURODIVERGENT_PATTERNS',
    'BIO_KEYWORDS',
    'CONSCIOUSNESS_TYPES',
    'TIME_PATTERNS',
    'TIME_CONVERSIONS',
    'IMPLICIT_TIME_INDICATORS',
    'IMPLICIT_TIME_VALUES',
    'PROFANITY_INDICATORS'
]